// Organic waveform — a continuous wavy line instead of vertical bars. The
// shape is generated by summing several sines with mismatched periods so it
// looks "alive" rather than mathematical. While playing/recording the line
// flows leftward via animated stroke-dashoffset.

interface WaveformProps {
  level: number;
  active: boolean;
  className?: string;
  variant?: "light" | "dark";
  /** points along the curve (more = smoother but heavier). */
  points?: number;
}

export const Waveform = ({
  level,
  active,
  className = "",
  variant = "dark",
  points = 64,
}: WaveformProps) => {
  const stroke = variant === "dark" ? "hsl(var(--leaf))" : "hsl(var(--canopy))";
  const halo = variant === "dark" ? "hsl(var(--leaf) / 0.18)" : "hsl(var(--canopy) / 0.12)";
  const W = 600;
  const H = 80;
  const mid = H / 2;

  // Build path: midpoint Y for each x, computed from a sum of sines. The
  // amplitude scales with `level` (live mic level) plus a baseline so the
  // waveform never collapses to a flat line.
  const baseAmp = active ? 6 + level * 26 : 5;
  const path: string[] = [];
  for (let i = 0; i <= points; i++) {
    const x = (i / points) * W;
    const t = i / points;
    // Three sines at incommensurate frequencies, plus a slow envelope
    // that makes the centre of the line "fatter" than the edges.
    const env = Math.sin(t * Math.PI); // 0 → 1 → 0
    const y =
      mid +
      env *
        baseAmp *
        (Math.sin(t * Math.PI * 9) * 0.6 +
          Math.sin(t * Math.PI * 17 + 1.3) * 0.3 +
          Math.sin(t * Math.PI * 31 + 0.7) * 0.2);
    path.push(`${i === 0 ? "M" : "L"} ${x.toFixed(2)} ${y.toFixed(2)}`);
  }
  const d = path.join(" ");

  return (
    <svg
      viewBox={`0 0 ${W} ${H}`}
      preserveAspectRatio="none"
      className={`h-16 w-full ${className}`}
      aria-hidden="true"
    >
      {/* Halo behind the line for soft glow */}
      <path
        d={d}
        stroke={halo}
        strokeWidth="6"
        fill="none"
        strokeLinecap="round"
        strokeLinejoin="round"
        style={{ filter: "blur(6px)" }}
      />
      {/* Main organic line */}
      <path
        d={d}
        stroke={stroke}
        strokeWidth="1.8"
        fill="none"
        strokeLinecap="round"
        strokeLinejoin="round"
        opacity={active ? 0.95 : 0.55}
        strokeDasharray={active ? "100 0" : undefined}
        className={active ? "animate-wave-flow" : undefined}
      />
      {/* Pulse dot at the leading edge when active */}
      {active && (
        <circle
          cx={W - 6}
          cy={mid}
          r="3.2"
          fill={stroke}
          className="animate-shimmer"
        />
      )}
    </svg>
  );
};
